# Generated by Django 4.0.4 on 2022-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del género', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione un genero', to='blog.genre'),
        ),
    ]
