# Generated by Django 4.0.4 on 2022-05-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_me_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='me_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
