# Generated by Django 4.0.4 on 2022-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_me_img_remove_post_genero_remove_post_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
