# Generated by Django 4.0.4 on 2022-05-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genero',
        ),
    ]
